export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "ABACAXI", tip: "Fruta com casca espinhosa e polpa amarela" },
  { id: 2, word: "ELEFANTE", tip: "Maior mamífero terrestre" },
  { id: 3, word: "BRASIL", tip: "Maior país da América do Sul" },
  { id: 4, word: "LUA", tip: "Satélite natural da Terra" },
  { id: 5, word: "SOL", tip: "Estrela no centro do Sistema Solar" },
  { id: 6, word: "MONTANHA", tip: "Grande elevação natural do terreno" },
  { id: 7, word: "OCEANO", tip: "Grande extensão de água salgada" },
  { id: 8, word: "GIRAFA", tip: "Animal conhecido pelo pescoço comprido" },
  { id: 9, word: "PINGUIM", tip: "Ave que não voa e vive em regiões frias" },
  { id: 10, word: "CANGURU", tip: "Animal marsupial típico da Austrália" },
  { id: 11, word: "BORBOLETA", tip: "Inseto que passa por metamorfose" },
  { id: 12, word: "LEAO", tip: "Conhecido como o rei da selva" },
  { id: 13, word: "TIGRE", tip: "Grande felino com listras" },
  { id: 14, word: "GOLFINHO", tip: "Mamífero marinho muito inteligente" },
  { id: 15, word: "BALEIA", tip: "Maior animal do planeta" },
  { id: 16, word: "FOGUETE", tip: "Veículo usado para viajar ao espaço" },
  { id: 17, word: "PLANETA", tip: "Corpo celeste que orbita uma estrela" },
  { id: 18, word: "GALAXIA", tip: "Conjunto de bilhões de estrelas" },
  { id: 19, word: "ESTRELA", tip: "Corpo celeste que emite luz própria" },
  { id: 20, word: "COMETA", tip: "Corpo celeste com longa cauda brilhante" },
  { id: 21, word: "DINOSSAURO", tip: "Animal pré-histórico extinto" },
  { id: 22, word: "VULCAO", tip: "Estrutura geológica que pode expelir lava" },
  { id: 23, word: "DESERTO", tip: "Região com pouca chuva" },
  { id: 24, word: "FLORESTA", tip: "Área com grande quantidade de árvores" },
  { id: 25, word: "CACHOEIRA", tip: "Queda natural de água" },
  { id: 26, word: "ARCOIRIS", tip: "Fenômeno colorido após a chuva" },
  { id: 27, word: "TEMPESTADE", tip: "Fenômeno com chuva intensa e raios" },
  { id: 28, word: "NEVE", tip: "Precipitação comum em regiões frias" },
  { id: 29, word: "GELO", tip: "Água em estado sólido" },
  { id: 30, word: "FOGO", tip: "Produz calor e luz durante a combustão" },
  { id: 31, word: "VIOLAO", tip: "Instrumento musical de cordas" },
  { id: 32, word: "PIANO", tip: "Instrumento musical com teclas" },
  { id: 33, word: "BATERIA", tip: "Instrumento formado por tambores e pratos" },
  { id: 34, word: "TROMPETE", tip: "Instrumento musical de sopro" },
  { id: 35, word: "FUTEBOL", tip: "Esporte mais popular do mundo" },
  { id: 36, word: "BASQUETE", tip: "Esporte jogado com cestas" },
  { id: 37, word: "NATACAO", tip: "Esporte praticado na água" },
  { id: 38, word: "VOLEI", tip: "Esporte em que a bola passa por cima da rede" },
  { id: 39, word: "XADREZ", tip: "Jogo de estratégia com peças" },
  { id: 40, word: "BICICLETA", tip: "Veículo de duas rodas movido por pedais" },
  { id: 41, word: "CARRO", tip: "Veículo de quatro rodas" },
  { id: 42, word: "AVIAO", tip: "Meio de transporte aéreo" },
  { id: 43, word: "NAVIO", tip: "Grande embarcação" },
  { id: 44, word: "TREM", tip: "Transporte que anda sobre trilhos" },
  { id: 45, word: "PONTE", tip: "Construção usada para atravessar rios" },
  { id: 46, word: "CASTELO", tip: "Construção medieval fortificada" },
  { id: 47, word: "BIBLIOTECA", tip: "Local onde há muitos livros" },
  { id: 48, word: "ESCOLA", tip: "Lugar destinado ao ensino" },
  { id: 49, word: "HOSPITAL", tip: "Local destinado ao atendimento de saúde" },
  { id: 50, word: "MUSEU", tip: "Local que preserva obras e objetos históricos" },
  { id: 51, word: "LIVRO", tip: "Objeto usado para leitura" },
  { id: 52, word: "CANETA", tip: "Objeto usado para escrever" },
  { id: 53, word: "LAPIS", tip: "Objeto usado para desenhar ou escrever" },
  { id: 54, word: "MOCHILA", tip: "Usada para transportar materiais" },
  { id: 55, word: "RELOGIO", tip: "Objeto usado para ver as horas" },
  { id: 56, word: "OCULOS", tip: "Ajuda pessoas a enxergar melhor" },
  { id: 57, word: "CAMISA", tip: "Peça de roupa para a parte superior do corpo" },
  { id: 58, word: "SAPATO", tip: "Calçado para os pés" },
  { id: 59, word: "CHAPEU", tip: "Acessório usado na cabeça" },
  { id: 60, word: "GUARDACHUVA", tip: "Protege da chuva" },
  { id: 61, word: "PIZZA", tip: "Prato típico da culinária italiana" },
  { id: 62, word: "HAMBURGUER", tip: "Sanduíche muito popular" },
  { id: 63, word: "CHOCOLATE", tip: "Doce feito a partir do cacau" },
  { id: 64, word: "SORVETE", tip: "Sobremesa gelada" },
  { id: 65, word: "QUEIJO", tip: "Alimento produzido a partir do leite" },
  { id: 66, word: "ARROZ", tip: "Alimento muito consumido no Brasil" },
  { id: 67, word: "FEIJAO", tip: "Companheiro tradicional do arroz" },
  { id: 68, word: "BANANA", tip: "Fruta amarela muito popular" },
  { id: 69, word: "MELANCIA", tip: "Fruta grande de casca verde" },
  { id: 70, word: "LARANJA", tip: "Fruta rica em vitamina C" },
  { id: 71, word: "TOMATE", tip: "Muito usado em saladas e molhos" },
  { id: 72, word: "CENOURA", tip: "Legume de cor alaranjada" },
  { id: 73, word: "BATATA", tip: "Ingrediente usado para fazer fritas" },
  { id: 74, word: "CEBOLA", tip: "Ingrediente que costuma fazer os olhos lacrimejarem" },
  { id: 75, word: "PIMENTA", tip: "Ingrediente conhecido pelo sabor picante" },
  { id: 76, word: "AMARELO", tip: "Cor do sol em muitos desenhos" },
  { id: 77, word: "AZUL", tip: "Cor do céu em um dia limpo" },
  { id: 78, word: "VERDE", tip: "Cor associada às plantas" },
  { id: 79, word: "VERMELHO", tip: "Cor frequentemente associada ao coração" },
  { id: 80, word: "ROXO", tip: "Cor formada pela mistura de azul e vermelho" },
  { id: 81, word: "FAMILIA", tip: "Grupo de pessoas unidas por parentesco" },
  { id: 82, word: "AMIZADE", tip: "Relação baseada em carinho e confiança" },
  { id: 83, word: "CORAGEM", tip: "Qualidade de enfrentar desafios" },
  { id: 84, word: "ALEGRIA", tip: "Sentimento de felicidade" },
  { id: 85, word: "ESPERANCA", tip: "Sentimento de acreditar em dias melhores" },
  { id: 86, word: "PACIENCIA", tip: "Virtude de saber esperar" },
  { id: 87, word: "LIBERDADE", tip: "Direito de agir dentro da lei e das escolhas" },
  { id: 88, word: "JUSTICA", tip: "Valor relacionado à igualdade e ao direito" },
  { id: 89, word: "RESPEITO", tip: "Valor essencial na convivência" },
  { id: 90, word: "HONESTIDADE", tip: "Qualidade de quem fala a verdade" },
  { id: 91, word: "CADERNO", tip: "Usado para fazer anotações" },
  { id: 92, word: "COMPUTADOR", tip: "Máquina usada para trabalhar e estudar" },
  { id: 93, word: "TELEFONE", tip: "Dispositivo usado para fazer chamadas" },
  { id: 94, word: "INTERNET", tip: "Rede mundial de computadores" },
  { id: 95, word: "CAMERA", tip: "Usada para tirar fotografias" },
  { id: 96, word: "ESPORTE", tip: "Atividade física com regras" },
  { id: 97, word: "CINEMA", tip: "Lugar para assistir filmes" },
  { id: 98, word: "PRAIA", tip: "Faixa de areia à beira do mar" },
  { id: 99, word: "PARQUE", tip: "Local para lazer ao ar livre" },
  { id: 100, word: "UNIVERSO", tip: "Conjunto de tudo o que existe" },
]